name: Build Vite App

on:
  push:
    branches:
      - main  # Change this if your main branch has a different name
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.0.0 # Change this based on your project requirements
          cache: npm

      - name: Install Dependencies
        run: npm install --legacy-peer-deps

      - name: Build Vite App
        run: npm run build

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist # Adjust this if your build output folder is different
